import '@/styles/globals.scss'
import type { Metadata } from 'next'
import { Bodoni_Moda } from 'next/font/google'
import { ReactNode } from 'react'

const bodoniModa = Bodoni_Moda({
    variable: '--font-bodoni-moda',
    subsets: ['latin'],
    weight: ['400', '700'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
interface RootLayoutProps {
    children: ReactNode
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
    return (
        <html className={bodoniModa.variable} lang='en'>
            <body>{children}</body>
        </html>
    )
}
